import CSkia
import Foundation

/**
 * `Canvas` provides an interface for drawing, and how the drawing is clipped and transformed.
 * `Canvas` contains a stack of `Matrix` and clip values.
 *
 * `Canvas` and `Paint` together provide the state to draw into `Surface` or `BaseDevice`.
 * Each `Canvas` draw call transforms the geometry of the object by the concatenation of all
 * `Matrix` values in the stack. The transformed geometry is clipped by the intersection
 * of all of clip values in the stack. The `Canvas` draw calls use `Paint` to supply drawing
 * state such as color, `Typeface`, text size, stroke width, `Shader` and so on.
 *
 * To draw to a pixel-based destination, create raster surface or GPU surface.
 * Request `Canvas` from `Surface` to obtain the interface to draw.
 * `Canvas` generated by raster surface draws to memory visible to the CPU.
 * `Canvas` generated by GPU surface uses Vulkan or OpenGL to draw to the GPU.
 *
 * To draw to a document, obtain `Canvas` from SVG canvas, document PDF, or `PictureRecorder`.
 * `Document` based `Canvas` and other `Canvas` subclasses reference `BaseDevice` describing the
 * destination.
 *
 * Typically you create the Canvas from a bitmap, but an empty canvas can be created with the
 * some fo the static `make` methods, and serve special purposes:
 * * `makeEmpty(width:height)` - creates an empty canvas that ignores all drawing commands
 * * `makeOverdraw(canvas:)` - A canvas that captures all drawing commands, and rather than draw
 *    the actual content, it increments the alpha channel of each pixel every time it would have been touched
 *    by a draw call.
 * * `makeNway(width:height:)` - will create a passthrough n-way canvas.  Once created you can add canvas with `addCanvas`, and remove them with `removeCanvas`
 */
public final class Canvas {
  var handle: OpaquePointer

  init(handle: OpaquePointer) {
    self.handle = handle
  }

  /**
   * Returns the number of saved states, each containing: `Matrix` and clip.
   * Equals the number of save() calls less the number of restore() calls plus one.
   * The save count of a new canvas is one.
   * - Returns: depth of save state stack
   * example: https://fiddle.skia.org/c/@Canvas_getSaveCount
   */
  public var saveCount: Int32 {
    sk_canvas_get_save_count(handle)
  }

  /**
   * Saves `Matrix` and clip.
   * Calling `restore` discards changes to `Matrix` and clip,
   * restoring the `Matrix` and clip to their state when `save` was called.
   *
   * `Matrix` may be changed by `translate`, `scale`, `rotate`, `skew`, `concat`,
   * `setMatrix`, and `resetMatrix` Clip may be changed by `clipRect`, `clipRRect`,
   * `clipPath`, `clipRegion`.
   *
   * Saved `Canvas` state is put on a stack; multiple calls to save() should be balance
   * by an equal number of calls to restore().
   * Call restoreToCount() with result to restore this and subsequent saves.
   * - Returns: depth of saved stack
   */
  @discardableResult public func save() -> Int32 {
    sk_canvas_save(handle)
  }

  /**
   * Saves `Matrix` and clip, and allocates a `Bitmap` for subsequent drawing.
   * Calling restore() discards changes to `Matrix` and clip, and draws the `Bitmap`.
   *
   * `Matrix` may be changed by `translate`, `scale`, `rotate`, `skew`, `concat`,
   * `setMatrix`, and `resetMatrix` Clip may be changed by `clipRect`, `clipRRect`,
   * `clipPath`, `clipRegion`.
   *
   * `SkRect` bounds suggests but does not define the `Bitmap` size. To clip drawing to
   * a specific rectangle, use clipRect().
   *
   * Optional `Paint` paint applies alpha, `ColorFilter`, `ImageFilter`, and
   * `BlendMode` when `restore` is called.
   *
   * Call `restoreToCount` with returned value to restore this and subsequent saves.
   * - Parameter limit: hint to limit the size of the layer; may be `nil`
   * - Parameter paint: graphics state for layer; may be `nil`
   * - Returns: depth of saved stack
   */
  public func saveLayer(limit: SkRect? = nil, paint: Paint? = nil) {
    let p = paint == nil ? nil : paint!.handle
    if let l = limit {
      var c = l
      withUnsafePointer(to: &c) { ptr in
        _ = sk_canvas_save_layer(handle, ptr, p)
      }
    } else {
      sk_canvas_save_layer(handle, nil, p)
    }
  }

  public func clear() {
    clear(color: SkColor(0x00000000))
  }

  /**
   * Fills clip with color color using `BlendMode`::kSrc.
   * This has the effect of replacing all pixels contained by clip with color.
   * - Parameter color: unpremultiplied ARGB
   */
  public func clear(color: SkColor) {
    sk_canvas_clear(handle, color)
  }

  /**
   * Removes changes to `Matrix` and clip since `Canvas` state was
   * last saved. The state is removed from the stack.
   * Does nothing if the stack is empty.
   * example: https://fiddle.skia.org/c/@AutoCanvasRestore_restore
   * example: https://fiddle.skia.org/c/@Canvas_restore
   */
  public func restore() {
    sk_canvas_restore(handle)
  }

  /**
   * Restores state to `Matrix` and clip values when `save()`, `saveLayer()`,
   * `saveLayerPreserveLCDTextRequests()`, or `saveLayerAlpha()` returned `count`.
   * Does nothing if `count` is greater than state stack count.
   * Restores state to initial values if `count` is less than or equal to one.
   * - Parameter count: depth of state stack to restore
   */
  public func restore(to count: Int32) {
    sk_canvas_restore_to_count(handle, count)
  }

  /**
   * Translates `Matrix` by dx along the x-axis and dy along the y-axis.
   * Mathematically, replaces `Matrix` with a translation matrix
   * premultiplied with `Matrix`.
   * This has the effect of moving the drawing by (dx, dy) before transforming
   * the result with `Matrix`.
   * - Parameter dx: distance to translate on x-axis
   * - Parameter dy: distance to translate on y-axis
   */
  public func translate(dx: Float, dy: Float) {
    sk_canvas_translate(handle, dx, dy)
  }

  /**
   * Scales `Matrix` by `scale` on the x-axis and  y-axis.
   * Mathematically, replaces `Matrix` with a scale matrix
   * premultiplied with `Matrix`.
   * This has the effect of scaling the drawing by (sx, sy) before transforming
   * the result with `Matrix`.
   * - Parameter scale: amount to scale on both axis
   */
  public func scale(_ scale: Float) {
    sk_canvas_scale(handle, scale, scale)
  }

  /**
   * Scales `Matrix` by sx on the x-axis and sy on the y-axis.
   * Mathematically, replaces `Matrix` with a scale matrix
   * premultiplied with `Matrix`.
   * This has the effect of scaling the drawing by (sx, sy) before transforming
   * the result with `Matrix`.
   * - Parameter sx: amount to scale on x-axis
   * - Parameter sy: amount to scale on y-axis
   */
  public func scale(sx: Float, sy: Float) {
    sk_canvas_scale(handle, sx, sy)
  }

  /**
   *
   * - Parameter pivot: the pivot point for the scale to take place
   */
  public func scale(sx: Float, sy: Float, pivot: SkPoint) {
    translate(dx: pivot.x, dy: pivot.y)
    scale(sx: sx, sy: sy)
    translate(dx: -pivot.x, dy: -pivot.y)
  }

  /**
   * Rotates `Matrix` by degrees. Positive degrees rotates clockwise.
   * Mathematically, replaces `Matrix` with a rotation matrix
   * premultiplied with `Matrix`.
   * This has the effect of rotating the drawing by degrees before transforming
   * the result with `Matrix`.
   * - Parameter degrees: amount to rotate, in degrees
   */
  public func rotate(degrees: Float) {
    sk_canvas_rotate(handle, degrees)
  }

  /**
   * Rotates `Matrix` by degrees about a point at `pivot`. Positive degrees rotates
   * clockwise.
   * Mathematically, constructs a rotation matrix; premultiplies the rotation matrix by
   * a translation matrix; then replaces `Matrix` with the resulting matrix
   * premultiplied with `Matrix`.
   * This has the effect of rotating the drawing about a given point before
   * transforming the result with `Matrix`.
   * - Parameter degrees: amount to rotate, in degrees
   * - Parameter pivot: point to rotate about
   */
  public func rotate(degrees: Float, x: Float, y: Float) {
    sk_canvas_rotate2(handle, degrees, x, y)
  }

  public func skew(sx: Float, sy: Float) {
    sk_canvas_skew(handle, sx, sy)
  }

  public func clip(x: Float = 0, y: Float = 0, width: Float, height: Float, op: ClipOp = .intersection, antialias: Bool = false) {
    withUnsafePointer(to: SkRect(x: x, y: y, width: width, height: height)) {
      sk_canvas_clip_rect(handle, $0, op.native(), antialias)
    }
  }

  public func clip(rect: SkRect, op: ClipOp = .intersection, antialias: Bool = false) {
    withUnsafePointer(to: rect) {
      sk_canvas_clip_rect(handle, $0, op.native(), antialias)
    }
  }

  /**
   * Draws line segment from p0 to p1 using clip, `Matrix`, and `Paint` paint.
   * In paint: `Paint` stroke width describes the line thickness;
   * `Paint.cap` draws the end rounded or square;
   * `Paint.style` is ignored, as if were set to `.stroke`
   * - Parameter p0: start of line segment
   * - Parameter p1: end of line segment
   * - Parameter paint: stroke, blend, color, and so on, used to draw
   */
  public func drawLine(p0: SkPoint, p1: SkPoint, _ paint: Paint) {
    sk_canvas_draw_line(handle, p0.x, p0.y, p1.x, p1.y, paint.handle)
  }

  /**
   * Draws line segment from (x0, y0) to (x1, y1) using clip, `Matrix`, and `Paint` paint.
   * In paint: `Paint` stroke width describes the line thickness;
   * `Paint.cap` draws the end rounded or square;
   * `Paint.style` is ignored, as if were set to `.stroke`
   * - Parameter x0: start of line segment on x-axis
   * - Parameter y0: start of line segment on y-axis
   * - Parameter x1: end of line segment on x-axis
   * - Parameter y1: end of line segment on y-axis
   * - Parameter paint: stroke, blend, color, and so on, used to draw
   */
  public func drawLine(x0: Float, y0: Float, x1: Float, y1: Float, _ paint: Paint) {
    sk_canvas_draw_line(handle, x0, y0, x1, y1, paint.handle)
  }

  public func draw(paint: Paint) {
    sk_canvas_draw_paint(handle, paint.handle)
  }

  public func drawRect(x: Float, y: Float, width: Float, height: Float, _ paint: Paint) {
    draw(rect: sk_rect_t(left: x, top: y, right: x + width, bottom: y + height), paint)
  }

  public func draw(rect: SkRect, _ paint: Paint) {
    withUnsafePointer(to: rect) { ptr in
      sk_canvas_draw_rect(handle, ptr, paint.handle)
    }
  }

  public func draw(rrect: RRect, _ paint: Paint) {
    sk_canvas_draw_rrect(handle, rrect.handle, paint.handle)
  }

  public func drawRRect(x: Float, y: Float, width: Float, height: Float, rx: Float, ry: Float, _ paint: Paint) {
    draw(rect: SkRect(left: x, top: y, right: x + width, bottom: y + height), rx: rx, ry: ry, paint)
  }

  public func draw(rect: SkRect, rx: Float, ry: Float, _ paint: Paint) {
    withUnsafePointer(to: rect) {
      sk_canvas_draw_rrect2(handle, $0, rx, ry, paint.handle)
    }
  }

  public func drawCircle(cx: Float, cy: Float, radius: Float, _ paint: Paint) {
    sk_canvas_draw_circle(handle, cx, cy, radius, paint.handle)
  }

  public func drawArc(oval: SkRect, startAngle: Float, sweepAngle: Float, useCenter: Bool = false, _ paint: Paint) {
    withUnsafePointer(to: oval) {
      sk_canvas_draw_arc(handle, $0, startAngle, sweepAngle, useCenter, paint.handle)
    }
  }

  public func draw(path: Path, _ paint: Paint) {
    sk_canvas_draw_path(handle, path.handle, paint.handle)
  }

  /// Draws text on the canvas at the specified coordinates.
  /// - Parameter text The text to draw.
  /// - Parameter x The x-coordinate of the origin of the text being drawn.
  /// - Parameter y The y-coordinate of the origin of the text being drawn.
  /// - Parameter font the font used to set the `text`
  /// - Parameter paint The paint to use when drawing the text.
  public func draw(text: String, x: Float, y: Float, font: Font, _ paint: Paint) {
    sk_canvas_draw_simple_text(handle, text, text.utf8.count, UTF8_SK_TEXTENCODING, x, y, font.handle, paint.handle)
  }

  /**
   * Draws `TextBlob` blob at (x, y), using clip, `Matrix`, and `Paint` paint.
   * blob contains glyphs, their positions, and paint attributes specific to text:
   * `Typeface`, `Paint` text size, `Paint` text scale x,
   * `Paint` text skew x, `Paint`::Align, `Paint`::Hinting, anti-alias, `Paint` fake bold,
   * `Paint` font embedded bitmaps, `Paint` full hinting spacing, LCD text, `Paint` linear text,
   * and `Paint` subpixel text.
   *
   * `TextEncoding` must be set to `TextEncoding`::kGlyphID.
   *
   * Elements of paint: anti-alias, `BlendMode`, color including alpha,
   * `SkColorFilter`, `Paint` dither, `DrawLooper`, `MaskFilter`, `PathEffect`, `Shader`, and
   * `Paint`::Style; apply to blob. If `Paint` contains `Paint`::kStroke_Style:
   * `Paint` miter limit, `Paint`::Cap, `Paint`::Join, and `Paint` stroke width;
   * apply to `Path` created from blob.
   *
   * - Parameter textblob Glyphs, positions, and their paints' text size, typeface, and so on
   * - Parameter x horizontal offset applied to blob
   * - Parameter y vertical offset applied to blob
   * - Parameter paint blend, color, stroking, and so on, used to draw
   */
  public func draw(textblob: Textblob, x: Float, y: Float, _ paint: Paint) {
    sk_canvas_draw_text_blob(handle, textblob.handle, x, y, paint.handle)
  }

  /// Draws an offset spot shadow and outlining ambient shadow for the given path using a disc light.
  /// The shadow may be cached, depending on the path type and canvas matrix.
  /// If the matrix is perspective or the path is volatile, it will not be cached.
  ///
  /// See also https://github.com/flutter/engine/blob/main/display_list/skia/dl_sk_dispatcher.cc#L273
  /// - Parameter canvas The canvas on which to draw the shadows
  /// - Parameter path The occluder used to generate the shadows
  /// - Parameter zPlaneParams Values for the plane function which returns the Z offset of the occluder from the canvas based on local x and y values (the current matrix is not applied)
  /// - Parameter lightPos Generally, the 3D position of the light relative to the canvas plane. If kDirectionalLight_ShadowFlag is set, this specifies a vector pointing towards the light
  /// - Parameter lightRadius Generally, the radius of the disc light. If `ShadowType.directionalLight` is set, this specifies the amount of blur when the occluder is at Z offset == 1. The blur will grow linearly as the Z value increases
  /// - Parameter ambientColor The color of the ambient shadow
  /// - Parameter spotColor The color of the spot shadow
  /// - Parameter flags Options controlling opaque occluder optimizations, shadow appearance, and light position. See `ShadowType`
  public func draw(shadow path: Path, zPlane: SkPoint3, lighting: SkPoint3, lightRadius: Float, ambientColor: SkColor, spotColor: SkColor, type: ShadowType) {
    withUnsafePointer(to: zPlane) { zPlanePtr in
      withUnsafePointer(to: lighting) { lightingPtr in
        sk_canvas_draw_shadow(handle, path.handle, zPlanePtr, lightingPtr, lightRadius, ambientColor, spotColor, type.native())
      }
    }
  }

  public func draw(shadow path: Path, color: SkColor, radius: Float, dx: Float, dy: Float) {
    let pointer = UnsafeMutablePointer<sk_matrix_t>.allocate(capacity: 1)
    sk_canvas_get_total_matrix(handle, pointer)
    let matrix = pointer.pointee
    let scaleX = sqrt(matrix.scaleX * matrix.scaleX + matrix.skewX * matrix.skewX)
    let scaleY = sqrt(matrix.scaleY * matrix.scaleY + matrix.skewY * matrix.skewY)
    let total = sqrt(scaleX * scaleY)
    pointer.deallocate()

    draw(shadow: path, zPlane: SkPoint3(x: 0, y: 0, z: 1), lighting: SkPoint3(x: -dx * scaleX, y: -dy * scaleY, z: 1), lightRadius: radius * total, ambientColor: color, spotColor: color, type: .directionalLight)
  }

  public func draw(paragraph: Paragraph, x: Float, y: Float) {
    paragraph.paint(in: self, x: x, y: y)
  }

  public func draw(image: Image, _ x: Float, _ y: Float, sampling: Image.Sampling, _ paint: Paint? = nil) {
    withUnsafePointer(to: sampling) {
      sk_canvas_draw_image(handle, image.handle, x, y, $0, paint?.handle)
    }
  }

  public func draw(image: Image, in dest: SkRect, center: SkIRect, mode: Image.FilterMode = .linear, _ paint: Paint? = nil) {
    withUnsafePointer(to: dest) { d in
      withUnsafePointer(to: center) { c in
        sk_canvas_draw_image_nine(handle, image.handle, c, d, mode.native(), paint?.handle)
      }
    }
  }

  public func draw(image: Image, in dest: SkRect, sampling: Image.Sampling, _ paint: Paint? = nil) {
    withUnsafePointer(to: dest) { d in
      withUnsafePointer(to: sampling) { s in
        sk_canvas_draw_image_rect(handle, image.handle, d, s, paint?.handle)
      }
    }
  }

//  public func drawImage(_ image: Image, source: SkRect, dest: SkRect, _ paint: Paint? = nil) {
//    withUnsafePointer(to: dest) { destPtr in
//      withUnsafePointer(to: source) { srcPtr in
//        sk_canvas_draw_image_rect(handle, image.handle, srcPtr, destPtr, paint == nil ? nil : paint!.handle)
//      }
//    }
//  }

//    public func drawPositionedText (_ text: String, _ points: [SkPoint], _ paint: Paint)
//    {
//        var nativePoints: [sk_point_t] = []
//        for x in points {
//            nativePoints.append(x.toNative ())
//        }
//
//        sk_canvas_draw_pos_text(handle, text, text.utf8CString.count, nativePoints, paint.handle)
//    }
//
//    public func drawTextOnPath (_ text: String, _ path: Path, _ hOffset: Float, _ vOffset: Float, _ paint: Paint)
//    {
//        sk_canvas_draw_text_on_path(handle, text, text.utf8CString.count, path.handle, hOffset, vOffset, paint.handle)
//    }
}

public extension Canvas {
  enum ClipOp: UInt32 {
    case difference,
         intersection

    func native() -> sk_clipop_t {
      sk_clipop_t(rawValue)
    }

    init(_ native: sk_clipop_t) {
      self.init(rawValue: native.rawValue)!
    }
  }
}
